#include <Leg_DuctNo1_Defaults.hxx>

#define DUCT_DEFAULT_IMPL(INDEX, PARAMETER, NAME, VALUE)	\
	const Leg_DuctNo1_Defaults::param Leg_DuctNo1_Defaults::PARAMETER(INDEX, NAME, (Standard_Real)VALUE)

namespace AutLib
{

	const Standard_Integer Leg_DuctNo1_Defaults::NB_SECTIONS(20);

	DUCT_DEFAULT_IMPL(1, OVERAL_LENGTH, "overalLength", 160.0);
	DUCT_DEFAULT_IMPL(2, BREADTH_AT_INLET, "breadthAtInlet", 35.0);
	DUCT_DEFAULT_IMPL(3, BREADTH_AT_OUTLET, "breadthAtOutlet", 20.0);
	DUCT_DEFAULT_IMPL(4, DEPTH_AT_INLET, "depthAtInlet", 15.0);
	DUCT_DEFAULT_IMPL(5, DEPTH_AT_OUTLET, "depthAtOutlet", 20.0);
	DUCT_DEFAULT_IMPL(6, HEIGHT_AT_OUTLET, "heightAtOutlet", 20.0);

	DUCT_DEFAULT_IMPL(7, MID_LOCATION, "midLocation", 0.5);

	DUCT_DEFAULT_IMPL(8, INLET_WIDTH, "inletWidth", 0);
	DUCT_DEFAULT_IMPL(9, INLET_SIDE_SLOPE, "inletSideSlope", 0.75);
	DUCT_DEFAULT_IMPL(10, INLET_UPPER_TIGHTNESS, "inletUpperTightness", 1.0);
	DUCT_DEFAULT_IMPL(11, INLET_LOWER_TIGHTNESS, "inletLowerTightness", 0.65);

	DUCT_DEFAULT_IMPL(12, MID_WIDTH, "midWidth", 0);
	DUCT_DEFAULT_IMPL(13, MID_SIDE_SLOPE, "midSideSlope", 0.5);
	DUCT_DEFAULT_IMPL(14, MID_UPPER_TIGHTNESS, "midUpperTightness", 0.25);
	DUCT_DEFAULT_IMPL(15, MID_LOWER_TIGHTNESS, "midLowerTightness", 0.25);

	DUCT_DEFAULT_IMPL(16, OUTLET_WIDTH, "outletWidth", 0);
	DUCT_DEFAULT_IMPL(17, OUTLET_SIDE_SLOPE, "outletSideSlope", 0.5);
	DUCT_DEFAULT_IMPL(18, OUTLET_UPPER_TIGHTNESS, "outletUpperTightness", 1.0);
	DUCT_DEFAULT_IMPL(19, OUTLET_LOWER_TIGHTNESS, "outletLowerTightness", 1.0);

	DUCT_DEFAULT_IMPL(20, BREADTH_INLET_OFFSET, "breadthInletOffset", 0);
	DUCT_DEFAULT_IMPL(21, BREADTH_INLET_RISE_WEIGHT, "breadthInletRiseWeight", 0);
	DUCT_DEFAULT_IMPL(22, BREADTH_INLET_WEIGHT, "breadthInletWeight", 0);
	DUCT_DEFAULT_IMPL(23, BREADTH_LEFT_TURNING_POSITION, "breadthLeftTurningPos", 0.5);
	DUCT_DEFAULT_IMPL(24, BREADTH_LEFT_TURNING_WIDTH, "breadthLeftTurningWidth", 1.0);
	DUCT_DEFAULT_IMPL(25, BREADTH_MID_OFFSET, "breadthMidOffset", 0.0);
	DUCT_DEFAULT_IMPL(26, BREADTH_MID_WIDTH, "breadthMidWidth", 0.4);
	DUCT_DEFAULT_IMPL(27, BREADTH_OUTLET_OFFSET, "breadthOutletOffset", 0.0);
	DUCT_DEFAULT_IMPL(28, BREADTH_OUTLET_RISE_WEIGTH, "breadthOutletRiseWeight", 0.0);
	DUCT_DEFAULT_IMPL(29, BREADTH_OUTLET_WEIGHT, "breadthOutletWeight", 0.0);
	DUCT_DEFAULT_IMPL(30, BREADTH_RIGHT_TURNING_POSITION, "breadthRightTurningPos", 0.5);
	DUCT_DEFAULT_IMPL(31, BREADTH_RIGHT_TURNING_WIDTH, "breadthRightTurningWidth", 1.0);

	DUCT_DEFAULT_IMPL(32, DEPTH_INLET_OFFSET, "depthInletOffset", 0);
	DUCT_DEFAULT_IMPL(33, DEPTH_INLET_RISE_WEIGHT, "depthhInletRiseWeight", 0);
	DUCT_DEFAULT_IMPL(34, DEPTH_INLET_WEIGHT, "depthhInletWeight", 0);
	DUCT_DEFAULT_IMPL(35, DEPTH_LEFT_TURNING_POSITION, "depthhLeftTurningPos", 0.5);
	DUCT_DEFAULT_IMPL(36, DEPTH_LEFT_TURNING_WIDTH, "depthhLeftTurningWidth", 1.0);
	DUCT_DEFAULT_IMPL(37, DEPTH_MID_OFFSET, "depthhMidOffset", 0.0);
	DUCT_DEFAULT_IMPL(38, DEPTH_MID_WIDTH, "depthhMidWidth", 0.4);
	DUCT_DEFAULT_IMPL(39, DEPTH_OUTLET_OFFSET, "depthhOutletOffset", 0.0);
	DUCT_DEFAULT_IMPL(40, DEPTH_OUTLET_RISE_WEIGTH, "depthhOutletRiseWeight", 0.0);
	DUCT_DEFAULT_IMPL(41, DEPTH_OUTLET_WEIGHT, "depthhOutletWeight", 0.0);
	DUCT_DEFAULT_IMPL(42, DEPTH_RIGHT_TURNING_POSITION, "depthhRightTurningPos", 0.5);
	DUCT_DEFAULT_IMPL(43, DEPTH_RIGHT_TURNING_WIDTH, "depthhRightTurningWidth", 1.0);

	DUCT_DEFAULT_IMPL(44, GEN_RISE_POINT, "genRisePoint", 0.6);
	DUCT_DEFAULT_IMPL(45, GEN_POSITION, "genPosition", 0.5);
	DUCT_DEFAULT_IMPL(46, GEN_RISE_TANGENT, "genRiseTangent", 0.3);
	DUCT_DEFAULT_IMPL(47, GEN_OUTLET_TANGENT, "genOutletTangent", 0.2);
}